version: "3"

volumes:
  database_vol:

services:
  app:
    container_name: tiny_url
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env.default
    volumes:
      - ./:/home/app
    ports:
      - '4000:80'

  database:
    container_name: tiny_url_database
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: tiny_url
    volumes:
      - database_vol:/var/lib/postgresql/data
