version: "3" 

services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env.default
    volumes:
      - ./:/home/app
    ports:
      - '4000:80'

  database:
    container_name: database
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: application
